### ISSUE TITLE
issue not sure which scipt is causing issue

### ISSUE THREAD

**Issue by Thedeadlyart** [SuperPyroManiac/SuperEvents#2]
first off thanks for the 2 mods the callouts and the events love them. i'm not sure if it is a issue with the latest update with Rockstar but just installed events and 1.0.1. so far the only one that is causing lspdfr to crash for me is the car fire. not the one from callouts but the one from the new events one. I did it 2 times. i'm still trying to run some tests. when I call the fire trucks and use stop the ped to stop traffic. after everything is done and I drive away when I get the distance for the stop the ped to release traffic on it's own it crash's. per rph/log look at line:
[9/18/2019 8:56:16 PM.249]
that is one of the crash's. I test'ed the fire trucks without the even and stopping traffic had no issues and tried stop traffic without fire truck and even did with one of the other events of yours no crash. seems like it is having a issue with removing the firetruck after the event is over and I get away from the location. trying to trigger the event again so I can test without doing the stop the oed stop traffic but now that event isn't triggering lol. 
if u don't get to look at it by tomorrow i'll try and look through the code and see if I can find whats causing it might be stop the ped not sure yet. i'll keep eye out for anything else.

**Comment by Thedeadlyart** [comment]
[RagePluginHook.log](https://github.com/SuperPyroManiac/SuperEvents/files/3629110/RagePluginHook.log)
 might help if I upload the log lol

**Comment by SuperPyroManiac** [comment]
I see there was a few crashes in there, only 1 was caused by SuperEvents. I'll look for all the details though.

**Comment by Thedeadlyart** [comment]
yea since the Rockstar updates some of the other scripts aren't being nice so looks like tomorrow after get off work i'll be removing mods and testing them one by one. I was thinking about just reinstalling everything for safe keeping. I been going through ur code and so far don't really see anything that would cause it. it might be stop the ped not sure yet. I like trouble shooting so will give me something to do lol.
if you ever have something u want someone to test out or anything let me know. i'm getting into streaming so hopefully i'll get all my mods to play nice by this weekend was gonna make some video's and i'll put some your new event stuff in it and callout's.

**Comment by SuperPyroManiac** [comment]
Alright so i'll start from the bottom and go up (Recent to old)

`[9/18/2019 9:19:11 PM.403] LSPD First Response: [TRACE] Thread PlayerArrest #1 initialized
[9/18/2019 9:19:11 PM.432] LSPD First Response: 
[9/18/2019 9:19:11 PM.432] LSPD First Response: ==============================
[9/18/2019 9:19:11 PM.432] LSPD First Response: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[9/18/2019 9:19:11 PM.432] LSPD First Response: ------------------------------
[9/18/2019 9:19:11 PM.432] LSPD First Response: Origin: Game fiber "PlayerArrest".
[9/18/2019 9:19:11 PM.432] LSPD First Response: ------------------------------
[9/18/2019 9:19:11 PM.432] LSPD First Response: Exception type: Rage.Exceptions.InvalidHandleableException
[9/18/2019 9:19:11 PM.432] LSPD First Response: Exception message: Operation is not valid because the specified  Rage.Ped is invalid.
[9/18/2019 9:19:11 PM.432] LSPD First Response: ------------------------------
[9/18/2019 9:19:11 PM.432] LSPD First Response: Inner exceptions:
[9/18/2019 9:19:11 PM.432] LSPD First Response: ------------------------------
[9/18/2019 9:19:11 PM.432] LSPD First Response: Stack trace:
[9/18/2019 9:19:11 PM.432] LSPD First Response: at Rage.Entity.get_Position()
[9/18/2019 9:19:11 PM.433] at 9FO\&G$\&`_7\]i||cQHK~t}8 c$.Ede:vM^Lq=HS]&~7N{-dbc^h(Ped , vi3E9|=e-LQ^Es'c7\[1Sdm3x% , Object ) in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\Entities\PedIntelligence.cs:line 320
[9/18/2019 9:19:11 PM.433] at =D-`Hd!SRI 7`b!C<>\]6z5Rh.4LWJ^FZ{)1<!\&N/hDGt2u3%{\*.Invoke(Ped ped, vi3E9|=e-LQ^Es'c7\[1Sdm3x% id, Object sender)
[9/18/2019 9:19:11 PM.433] at =D-`Hd!SRI 7`b!C<>\]6z5Rh.{9Z3Lb@@fd{exGL^}6@4#D7r#(Ped , Object ) in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\Events.cs:line 238
[9/18/2019 9:19:11 PM.433] at fR%xhQ}6\\6w/3\,QL:3?5>wK\*(.u%$x=')+*O$*'QW\$O/yJ$Fa'() in E:\GTA V\LSPD First Response\LSPD First Response\Mod\PlayerArrest.cs:line 350
[9/18/2019 9:19:11 PM.433] at ;\.>:mY5}Y:\.)\[M:w~IFo^V#K#.KV3!r3\rC``=tD(1K@`T%/!L&() in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\ThreadedScriptComponent.cs:line 66
[9/18/2019 9:19:11 PM.433] at Rage.GameFiber.Main()
[9/18/2019 9:19:11 PM.433] LSPD First Response: ==============================`

This happened because someone was being arrested, but did not exist anymore. SuperEvents logged it was ready to spawn an event but never spawned one because it looks like you were in a callout.
Next:
`[9/18/2019 9:12:49 PM.880] LSPD First Response: [Better EMS]: Settings loaded from I:\SteamLibrary\steamapps\common\Grand Theft Auto V\Plugins\LSPDFR\BetterEMS.ini
[9/18/2019 9:12:49 PM.880] LSPD First Response: [Better EMS]: Unloaded Better EMS
[9/18/2019 9:12:49 PM.887] LSPD First Response: [FATAL] Exception while unloading: System.ArgumentException: An item with the same key has already been added.
[9/18/2019 9:12:49 PM.887] at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
[9/18/2019 9:12:49 PM.887] at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
[9/18/2019 9:12:49 PM.887] at LSPDFRComesAlive.AmbientEvent.⁬⁫‌⁫‎⁯‎⁮⁯⁯​‬⁪⁯⁬⁪‭⁭‫⁫‍‮‬‌‍‎⁪‍‫‌‮‫​‮‍‏⁮‍‫⁪‮() in D:\Darkmyre Gaming\LSPDFRComesAlive\LSPDFRComesAlive\AmbientEvent.cs:line 59
[9/18/2019 9:12:49 PM.887] at LSPDFRComesAlive.Main.‫‏​⁫‮‭‭‌⁯⁭⁪⁮‮⁭⁮⁮⁯‮‍⁫⁯‎‌‎⁪‫‫‪⁮‎⁯‪‭‪‫‬⁯‪‌‬‮(Boolean ) in D:\Darkmyre Gaming\LSPDFRComesAlive\LSPDFRComesAlive\Main.cs:line 40
[9/18/2019 9:12:49 PM.887] at LSPD_First_Response.Mod.API.Functions.OnDutyStateChangedEventHandler.Invoke(Boolean onDuty)
[9/18/2019 9:12:49 PM.887] at vz<sf-JU2Fv}2/BG F:)@\.uc\,.~eqvEbB]!4K\i9V"F++6Z5$6%(Boolean ) in E:\GTA V\LSPD First Response\LSPD First Response\Mod\PlayerDutyController.cs:line 64
[9/18/2019 9:12:49 PM.887] at 'fa"e3\[_m\,LT~8!N6n)jxx6|'.OnUnload(Boolean isTerminating) in E:\GTA V\LSPD First Response\LSPD First Response\Mod\LSPDFR.cs:line 702
[9/18/2019 9:12:49 PM.999] LSPD First Response: [INFO] LSPDFR has shut down`

This was caused by BetterEMS - conflicting keys.
Next:
`[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: ==============================
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: ------------------------------
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: Origin: Game fiber "<UNNAMED THREAD>".
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: ------------------------------
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: Exception type: System.MissingMethodException
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: Exception message: Method not found: 'DarkmyreAPI.ExtendedSpawnPoint DarkmyreAPI.Do.GetNearestSpawn(System.String, Rage.Vector3)'.
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: ------------------------------
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: Inner exceptions:
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: ------------------------------
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: Stack trace:
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: at GTAComesAlive.Ambience.CarBomb.<>c__DisplayClass0_0.<Main>b__0()
[9/18/2019 9:04:54 PM.999] at Rage.GameFiber.Main()
[9/18/2019 9:04:54 PM.999] GTA Comes Alive!: ==============================`

This was caused by GTA Comes Alive. Looks like you are missing an API or dependency of the plugin. Possibly just an issue with the plugin itself.
Next:
`[9/18/2019 9:01:02 PM.269] LSPD First Response: STP: TOW SERVICE IS FULLY DISMISSED
[9/18/2019 9:01:04 PM.407] LSPD First Response: LSPDFR might have crashed and STP cannot activate traffic control 
[9/18/2019 9:01:04 PM.635] LSPD First Response: 
[9/18/2019 9:01:04 PM.635] LSPD First Response: ==============================
[9/18/2019 9:01:04 PM.635] LSPD First Response: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[9/18/2019 9:01:04 PM.635] LSPD First Response: ------------------------------
[9/18/2019 9:01:04 PM.635] LSPD First Response: Origin: Game fiber "<UNNAMED THREAD>".
[9/18/2019 9:01:04 PM.635] LSPD First Response: ------------------------------
[9/18/2019 9:01:04 PM.635] LSPD First Response: Exception type: Rage.Exceptions.InvalidHandleableException
[9/18/2019 9:01:04 PM.635] LSPD First Response: Exception message: Operation is not valid because the specified  Rage.ISpatial is invalid.
[9/18/2019 9:01:04 PM.635] LSPD First Response: ------------------------------
[9/18/2019 9:01:04 PM.635] LSPD First Response: Inner exceptions:
[9/18/2019 9:01:04 PM.635] LSPD First Response: ------------------------------
[9/18/2019 9:01:04 PM.635] LSPD First Response: Stack trace:
[9/18/2019 9:01:04 PM.635] LSPD First Response: at Rage.Entity.DistanceTo(ISpatial spatialObject)
[9/18/2019 9:01:04 PM.635] at SuperEvents.Events.CarFire.<MainLogic>b__7_0()
[9/18/2019 9:01:04 PM.635] at Rage.GameFiber.Main()`

This was caused by SuperEvents. As of writing this i've just fixed it and will include it in the next update.
It looks like what happened was the tow truck took the car and despawned it. Now my plugin runs a loop checking your distance to the car and if you are more than 200 meters away it ends the event. Well in this case the car was despawned, and when the loop went to check your distance to it there was no car, so it flipped out and crashed. I added a simple check to make sure if the car exists and if not end, but if it does, then check the distance. If that makes sense.

**Comment by SuperPyroManiac** [comment]
I'm going to double check all the other events for the same issue now.

**Comment by Thedeadlyart** [comment]
sounds good thanks for the info. yea i'm removing the gta comes alive cause it is just like your events. next time I won't put long log was just trying to get log for several bugs and issues to get cleaned up on my side. keep up the good work.
